/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import business.Server;
import domain.Candidato;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nelson
 */
public class ContabilizarVotos extends javax.swing.JPanel {

    private Server server;
    private int numberIteration;
    private List<Candidato> ganadores;
    private List<Candidato> perdedores;
    private List<Candidato> postulantes;
    private DefaultTableModel model;
    /**
     * Creates new form ContabilizarVotos
     * @param server
     */
    public ContabilizarVotos(Server server) {
        initComponents();
        this.server = server;
        this.numberIteration = 0;
        this.model = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonIteraciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        buttonIteraciones.setText("Proxima iteración");
        buttonIteraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIteracionesActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteración", "Candidato", "Votos", "Condición"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(buttonIteraciones)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(buttonIteraciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIteracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIteracionesActionPerformed
        Grafica grafica = new Grafica();
        grafica.graficar(server);
        int respond = server.contar_votos();
        server.dar_ganadores();
        if (respond == 1){
            
        } else {
            JOptionPane.showMessageDialog(null, "No existen más iteraciones");
        }      
        ganadores = server.getGanadores();
        System.out.println(ganadores.size());
        perdedores = server.getPerdedores();
        postulantes = server.getPostulantes();            
        fillTable();
    }//GEN-LAST:event_buttonIteracionesActionPerformed

    public void fillTable(){   
        String [] encabezado = {"Iteración", "Candidato", "Votos", "Condición"};
        String [][] infoCandidatos = new String[ganadores.size() + perdedores.size() + postulantes.size()][4];
        int j = 0;
        for (int i = 0; i < ganadores.size(); i++) {
            infoCandidatos[j][0] = numberIteration + "";
            infoCandidatos[j][1] = ganadores.get(i).getNombre();
            infoCandidatos[j][2] = ganadores.get(i).mis_votos.size() + "";
            infoCandidatos[j++][3] = "Ganador";      
            System.out.println("--------------------------------------------");
        }
        
        for (int i = 0; i < perdedores.size(); i++) {
            infoCandidatos[j][0] = numberIteration + "";
            infoCandidatos[j][1] = perdedores.get(i).getNombre();
            infoCandidatos[j][2] = perdedores.get(i).mis_votos.size() + "";
            infoCandidatos[j++][3] = "Perdedor";
        }
                
        for (int i = 0; i < postulantes.size(); i++) {
            infoCandidatos[j][0] = numberIteration++ + "";
            infoCandidatos[j][1] = postulantes.get(i).getNombre();
            infoCandidatos[j][2] = postulantes.get(i).mis_votos.size() + "";
            infoCandidatos[j++][3] = "Postulante";
        }
        model.setDataVector(infoCandidatos, encabezado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIteraciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
