package view;

import business.Server;
import domain.Candidato;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class CreateCandidateView extends javax.swing.JPanel {

    private ArrayList<Candidato> Pretendientes;
    private Server server;
    private PrincipalWindow principalWindow;
    /**
     * Creates new form CreateCandidateView
     * @param pServer
     * @param principalWindow
     */
    public CreateCandidateView(Server pServer, PrincipalWindow principalWindow) {
        initComponents();
        this.server = pServer;
        this.principalWindow = principalWindow;
        this.Pretendientes = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        ListaCandidatos = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Ingrese los candidatos para el puesto");

        BotonAgregar.setText("Agregar Candidato");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonEliminar.setText("Eliminar Candidato");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        ListaCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCandidatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(BotonAgregar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonEliminar))
                        .addComponent(ListaCandidatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(ListaCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar)
                    .addComponent(BotonEliminar))
                .addContainerGap(297, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        if (server.getPuesto() != null){
            if(Pretendientes.size() == server.getPuesto().getNumeroPostulantes()){
                JOptionPane.showMessageDialog(null,"Ya no se puede ingresar mas candidatos");
            }else{
                NewCandidateView candidateView = new NewCandidateView(server, principalWindow, this);
                principalWindow.addPanel(candidateView);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe de crear un puesto primero");
        }
    }//GEN-LAST:event_BotonAgregarActionPerformed
    
    public void addCandidato(Candidato candidato){
        ListaCandidatos.addItem(candidato);
    }
    
    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        Candidato candidatoAEliminar = (Candidato) ListaCandidatos.getSelectedItem();
        
        ListaCandidatos.removeItem(candidatoAEliminar);
        Pretendientes.remove(candidatoAEliminar);        
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void ListaCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCandidatosActionPerformed

    }//GEN-LAST:event_ListaCandidatosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JComboBox<Candidato> ListaCandidatos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
