/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import business.Server;
import domain.Puesto;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class CreatePositionView extends javax.swing.JPanel {

    private Server server;
    private PrincipalWindow principalWindow;
    /**
     * Creates new form CreatePositionView
     * @param pServer
     * @param principalWindow
     */
    public CreatePositionView(Server pServer, PrincipalWindow principalWindow) {
        initComponents();
        this.server = pServer;
        init();
        this.principalWindow = principalWindow;
    }
    
    private void init(){
        if (server.getPuesto() != null){
            nombreIngresado.setText(server.getPuesto().getNombre());
            organizacionIngresada.setText(server.getPuesto().getOrganizacion());
            puestosAsignadosIngresados.setText("" + server.getPuesto().getNumeroSillas());
            cantMaxPostuladosIngresada.setText("" + server.getPuesto().getNumeroPostulantes());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreIngresado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        organizacionIngresada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        puestosAsignadosIngresados = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantMaxPostuladosIngresada = new javax.swing.JTextField();
        BotonContinuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        nombreIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreIngresadoActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese la organización a la que pertenece el puesto");

        jLabel4.setText("Ingrese la cantidad de puestos asignables");

        puestosAsignadosIngresados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                puestosAsignadosIngresadosKeyTyped(evt);
            }
        });

        jLabel5.setText("Ingrese la cantidad máxima de postulados");

        cantMaxPostuladosIngresada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantMaxPostuladosIngresadaActionPerformed(evt);
            }
        });
        cantMaxPostuladosIngresada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantMaxPostuladosIngresadaKeyTyped(evt);
            }
        });

        BotonContinuar.setText("Continuar");
        BotonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonContinuarActionPerformed(evt);
            }
        });

        jLabel1.setText("Gestion de Puestos");

        jLabel2.setText("Ingrese el nombre del puesto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(nombreIngresado)
                            .addComponent(organizacionIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puestosAsignadosIngresados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantMaxPostuladosIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonContinuar)
                        .addGap(358, 358, 358))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(organizacionIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puestosAsignadosIngresados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantMaxPostuladosIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonContinuar)
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreIngresadoActionPerformed

    private void puestosAsignadosIngresadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_puestosAsignadosIngresadosKeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_puestosAsignadosIngresadosKeyTyped

    private void cantMaxPostuladosIngresadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantMaxPostuladosIngresadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantMaxPostuladosIngresadaActionPerformed

    private void cantMaxPostuladosIngresadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantMaxPostuladosIngresadaKeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_cantMaxPostuladosIngresadaKeyTyped

    private void BotonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonContinuarActionPerformed
        if(!nombreIngresado.getText().isEmpty()){
            if(!organizacionIngresada.getText().isEmpty()){
                if(!puestosAsignadosIngresados.getText().isEmpty()){
                    if(!cantMaxPostuladosIngresada.getText().isEmpty()){
                        int puestosAsignadosIngresadosEntero = Integer.parseInt(puestosAsignadosIngresados.getText());
                        int cantMaxPostuladosIngresadaEntero = Integer.parseInt(cantMaxPostuladosIngresada.getText());
                        String nombre = nombreIngresado.getText();
                        String organizacion = organizacionIngresada.getText();
                        
                        if(puestosAsignadosIngresadosEntero < cantMaxPostuladosIngresadaEntero){
                            if(puestosAsignadosIngresadosEntero == 0){
                                JOptionPane.showMessageDialog(null,"Por favor ingrese una cantidad de puestos asignables mayor a cero");
                            }else{
                                Puesto puesto = new Puesto(nombre, organizacion, puestosAsignadosIngresadosEntero, cantMaxPostuladosIngresadaEntero);
                                server.setPuesto(puesto);
                                
                                CreateCandidateView candidateView = new CreateCandidateView(server, principalWindow);
                                principalWindow.addPanel(candidateView);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null,"La cantidad maxima de candidatos que pueden participar por el puesto debe ser mayor a la cantidad de puestos asignables");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Por favor ingrese una cantidad maxima de pretendientes al puesto");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Por favor ingrese una cantidad de puestos asignables");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Por favor ingrese una organización para el puesto");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Por favor ingrese un nobre para el puesto");
        }
    }//GEN-LAST:event_BotonContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonContinuar;
    private javax.swing.JTextField cantMaxPostuladosIngresada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreIngresado;
    private javax.swing.JTextField organizacionIngresada;
    private javax.swing.JTextField puestosAsignadosIngresados;
    // End of variables declaration//GEN-END:variables
}
