package view;

import business.Server;
import domain.Candidato;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import java.awt.image.WritableRaster;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class NewCandidateView extends javax.swing.JPanel{

    private JFileChooser seleccion = new JFileChooser();
    private File archivo;
    private byte[] bytesImagen;
    private Color color;
    private boolean puedeContinuar;
    private Candidato candidatoACrear;
    private PrincipalWindow principalWindow;

    private Server server;
    private final CreateCandidateView candidateView;

    /**
     * Creates new form NewCandidateView
     *
     * @param pServer
     * @param principalWindow
     * @param candidateView
     */
    public NewCandidateView(Server pServer, PrincipalWindow principalWindow, CreateCandidateView candidateView) {
        initComponents();
        this.server = pServer;
        this.principalWindow = principalWindow;
        this.candidatoACrear = new Candidato();
        this.candidateView = candidateView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarCandidato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Canvas = new javax.swing.JLabel();
        nombreIngresado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        agrupacionIngresada = new javax.swing.JTextField();
        BotonAgregarImagen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BotonAgregarColor = new javax.swing.JButton();
        CanvasColor = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        AgregarCandidato.setText("Agregar");
        AgregarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCandidatoActionPerformed(evt);
            }
        });

        jLabel1.setText("Por favor especifique las caracteristicas del candidato");

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jScrollPane1.setViewportView(Canvas);

        jLabel3.setText("Agrupacíon Política");

        BotonAgregarImagen.setText("Agregar Imagen");
        BotonAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarImagenActionPerformed(evt);
            }
        });

        jLabel4.setText("Agregue la imagen del Candidato");

        jLabel6.setText("Agregue el color de la agrupación");

        BotonAgregarColor.setText("Agregar Color");
        BotonAgregarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarColorActionPerformed(evt);
            }
        });

        CanvasColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        javax.swing.GroupLayout CanvasColorLayout = new javax.swing.GroupLayout(CanvasColor);
        CanvasColor.setLayout(CanvasColorLayout);
        CanvasColorLayout.setHorizontalGroup(
            CanvasColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        CanvasColorLayout.setVerticalGroup(
            CanvasColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nombreIngresado))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(agrupacionIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(AgregarCandidato))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(BotonAgregarImagen))
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel6)
                                .addGap(58, 242, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Cancelar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(BotonAgregarColor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(CanvasColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(agrupacionIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregarImagen)
                    .addComponent(BotonAgregarColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(CanvasColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(AgregarCandidato))
                .addGap(158, 158, 158))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCandidatoActionPerformed
        if (!nombreIngresado.getText().isEmpty()) {
            if (!agrupacionIngresada.getText().isEmpty()) {
                if (candidatoACrear.getColor() != 0) {
                    if (candidatoACrear.getFoto() != null) {
                        candidatoACrear.setNombre(nombreIngresado.getText());
                        candidatoACrear.setAgrupacion(agrupacionIngresada.getText());
                        server.addPostulante(candidatoACrear);
                        
                        candidateView.addCandidato(candidatoACrear);                                                
                        principalWindow.addPanel(candidateView);                                                
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor ingrese una foto del candidato");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor ingrese el color representante del candidato");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese la agrupación política del candidato");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el nombre del candidato");
        }
    }//GEN-LAST:event_AgregarCandidatoActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        CreateCandidateView candidateView = new CreateCandidateView(server, principalWindow);
        principalWindow.addPanel(candidateView);
    }//GEN-LAST:event_CancelarActionPerformed

    private void BotonAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarImagenActionPerformed
        if (seleccion.showDialog(null, "Selección de imagen") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccion.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png")) {
                    try {
                        Canvas.setIcon(new ImageIcon(archivo.getAbsolutePath()));
                        
                        BufferedImage bufferedImage = ImageIO.read(archivo.getAbsoluteFile());
                        
                        // get DataBufferBytes from Raster
                        WritableRaster raster = bufferedImage .getRaster();
                        DataBufferByte data   = (DataBufferByte) raster.getDataBuffer();
                        
                        candidatoACrear.setFoto(data.getData());
                        candidatoACrear.setFotoPath(archivo.getAbsolutePath());
                    } catch (IOException ex) {
                        Logger.getLogger(NewCandidateView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo jpg o png");
                    archivo = null;
                }
            }
        }
    }//GEN-LAST:event_BotonAgregarImagenActionPerformed

    private void BotonAgregarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarColorActionPerformed
        color = JColorChooser.showDialog(null, "Seleccione un Color", Color.BLUE);
        CanvasColor.setBackground(color);
        candidatoACrear.setColor(color.getRGB());
    }//GEN-LAST:event_BotonAgregarColorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCandidato;
    private javax.swing.JButton BotonAgregarColor;
    private javax.swing.JButton BotonAgregarImagen;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Canvas;
    private javax.swing.JPanel CanvasColor;
    private javax.swing.JTextField agrupacionIngresada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreIngresado;
    // End of variables declaration//GEN-END:variables
}
