package view;

import business.Server;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author Nelson
 */
public class PrincipalWindow extends javax.swing.JFrame implements ActionListener{

    private JPanel contentPane;
    private Server server;
    private JMenuItem loadFileItem;
    private JMenuItem createPositionItem;
    private JMenuItem addCandidateItem;
    private JMenuItem setVotingPeriodItem;
    /**
     * Creates new form PrincipalWindow
     * @param pServer
     */
    public PrincipalWindow(Server pServer) {
        initComponents();
        this.server = pServer;
        init();        
    }

    private void init(){
        setResizable(false);
        setLocationRelativeTo(null);
        
        contentPane = new JPanel();
        contentPane.setBackground(Color.white);
        setContentPane(contentPane);
        contentPane.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));        
        
        JMenuBar menuBar = new JMenuBar();
        
        JMenu loadFileMenu = new JMenu("Padrón");
        loadFileItem = new JMenuItem("Cargar");
        loadFileItem.addActionListener(this);
        loadFileMenu.add(loadFileItem);        
        
        JMenu createPositionMenu = new JMenu("Puestos");
        createPositionItem = new JMenuItem("Crear o modificar");
        createPositionItem.addActionListener(this);
        createPositionMenu.add(createPositionItem);        
        
        JMenu addCandidateMenu = new JMenu("Candidatos");
        addCandidateItem = new JMenuItem("Añadir");
        addCandidateItem.addActionListener(this);
        addCandidateMenu.add(addCandidateItem);        
        
        JMenu setVotingPeriodMenu = new JMenu("Horario de votacion");
        setVotingPeriodItem = new JMenuItem("Definir periodo");
        setVotingPeriodItem.addActionListener(this);
        setVotingPeriodMenu.add(setVotingPeriodItem);        
        
        menuBar.add(loadFileMenu);
        menuBar.add(createPositionMenu);
        menuBar.add(addCandidateMenu);
        menuBar.add(setVotingPeriodMenu);
        
        contentPane.getParent().add(menuBar).setBounds(0, 0, 820, 20);
        
        LoadPersonsView loadPersons = new LoadPersonsView(server, this);
        addPanel(loadPersons);
    }
    
    public void addPanel(JPanel panel){
        contentPane.removeAll();
        contentPane.add(panel).setBounds(0, 20, 800, 600);     
        contentPane.repaint();
        contentPane.updateUI();
        contentPane.getParent().repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == loadFileItem){
            LoadPersonsView loadPersonsView = new LoadPersonsView(server, this);
            addPanel(loadPersonsView);
        } else if (e.getSource() == createPositionItem){
            CreatePositionView createPositionView = new CreatePositionView(server, this);
            addPanel(createPositionView);
        } else if (e.getSource() == addCandidateItem){
            CreateCandidateView candidateView = new CreateCandidateView(server, this);
            addPanel(candidateView);
        } else if (e.getSource() == setVotingPeriodItem){
            VotingPeriodView votingPeriodView = new VotingPeriodView(server, this);
            addPanel(votingPeriodView);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
